trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:80
    timeout: 1s
  grpc:
    addr: 0.0.0.0:0
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:55882664@tcp(47.107.95.82:3307)/d_storage?charset=utf8&parseTime=True&loc=Local
  redis:
    addr: 47.107.95.82:6379
    password: "55882664"
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  key: some-secret-key

mail:
  smtp_host: smtp.qq.com
  username: yuaniun@qq.com
  password: vwenjevfadocbfjj

