// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"banana/app/common/service/internal/biz"
	"banana/app/common/service/internal/conf"
	"banana/app/common/service/internal/data"
	"banana/app/common/service/internal/server"
	"banana/app/common/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	commonRepo := data.NewCommonRepo(dataData, logger)
	commonCase := biz.NewCommonCase(commonRepo, logger)
	commonService := service.NewCommonService(commonCase, logger)
	httpServer := server.NewHTTPServer(confServer, commonService)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
