#trace:
#  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:80
    timeout: 1s
  grpc:
    addr: 0.0.0.0:0
    timeout: 1s
data:
  minio:
    end_points: 172.20.0.6:9000
    access_key_id: banana
    secret_access_key: "55882664"
  database:
    driver: mysql
    source: root:55882664@tcp(47.107.95.82:3307)/d_storage?charset=utf8&parseTime=True&loc=Local
  redis:
    addr: 47.107.95.82:6379
    password: "55882664"
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s

