// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"banana/app/account-center/service/internal/biz"
	"banana/app/account-center/service/internal/conf"
	"banana/app/account-center/service/internal/data"
	"banana/app/account-center/service/internal/server"
	"banana/app/account-center/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, mail *conf.Mail, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, mail, logger)
	if err != nil {
		return nil, nil, err
	}
	accountCenterRepo := data.NewAccountCenterRepo(dataData, logger)
	accountCenterCase := biz.NewAccountCenterCase(accountCenterRepo, logger)
	accountCenterService := service.NewAccountCenterService(accountCenterCase, logger)
	httpServer := server.NewHTTPServer(confServer, accountCenterService)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
